import { ArrowLeft, CheckCircle2, CreditCard, Landmark, ShieldCheck, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ROUTES } from "@/routes/paths";
import OtpInput from "@/components/auth/OtpInput";
import Button from "@/components/common/Button";
import CopyButton from "@/components/common/CopyButton";
import ErrorState from "@/components/common/ErrorState";
import FormField from "@/components/common/FormField";
import Input from "@/components/common/Input";
import PullToRefresh from "@/components/common/PullToRefresh";
import DepositCashAppPayKit from "@/components/payments/DepositCashAppPayKit";
import { useAccountSummary } from "@/hooks/useDashboard";
import { useAuthorizeDepositPayment, useCompleteCashAppDepositApproval, useConfiguredProviders, useCreateDeposit, useDeposit, useInitializeDepositPayment, useVerifyDepositPayment } from "@/hooks/useDeposits";
import type { Deposit, DepositCheckout, PaymentProviderName } from "@/types/deposits";
import { formatCurrency } from "@/utils/formatCurrency";
import { paymentError, providerLabel, stepUpRequired } from "@/utils/payment";
type Screen="amount"|"provider"|"verify"|"checkout"|"cashapp"|"success"|"pending"|"failed";
function ProviderIcon({provider}:{provider:PaymentProviderName}){return provider==="paypal"?<WalletCards size={20}/>:provider==="paystack"?<Landmark size={20}/>:<CreditCard size={20}/>;}
export default function DepositPage(){
 const navigate=useNavigate(),accountQ=useAccountSummary(),providersQ=useConfiguredProviders(),createM=useCreateDeposit(),initM=useInitializeDepositPayment(),authorizeM=useAuthorizeDepositPayment(),verifyM=useVerifyDepositPayment(),cashAppM=useCompleteCashAppDepositApproval();
 const [screen,setScreen]=useState<Screen>("amount"),[amount,setAmount]=useState(""),[deposit,setDeposit]=useState<Deposit|null>(null),depositQ=useDeposit(deposit?.id??null),[provider,setProvider]=useState<PaymentProviderName|null>(null),[checkout,setCheckout]=useState<DepositCheckout|null>(null),[idempotencyKey,setIdempotencyKey]=useState(()=>crypto.randomUUID()),[error,setError]=useState(""),[code,setCode]=useState(""),[recoveryMode,setRecoveryMode]=useState(false);
 useEffect(()=>{if(!provider&&providersQ.data?.length)setProvider(providersQ.data[0]);},[provider,providersQ.data]);
 const numericAmount=Number(amount),validAmount=Number.isFinite(numericAmount)&&numericAmount>0,projectedBalance=useMemo(()=>!accountQ.data||!validAmount?null:Number(accountQ.data.available_balance)+numericAmount,[accountQ.data,numericAmount,validAmount]);
 async function refresh(){await Promise.all([accountQ.refetch(),providersQ.refetch(),deposit?depositQ.refetch():Promise.resolve()]);}
 async function continueFromAmount(){if(!validAmount)return;setError("");try{const item=await createM.mutateAsync({amount,idempotencyKey});setDeposit(item);setScreen("provider");}catch(e){setError(paymentError(e));}}
 async function initializePayment(stepUpAuthorization?:string){if(!deposit||!provider)return;setError("");try{const result=await initM.mutateAsync({depositId:deposit.id,provider,stepUpAuthorization});setCheckout(result);if(result.provider==="cashapp"&&result.checkout_data?.flow==="paykit"){setScreen("cashapp");return;}if(result.authorization_url){window.open(result.authorization_url,"_blank","noopener,noreferrer");setScreen("checkout");return;}setError("The payment provider did not return a checkout method.");}catch(e){if(stepUpRequired(e)&&!stepUpAuthorization){setScreen("verify");return;}setError(paymentError(e));}}
 async function verifyStepUp(){setError("");try{const a=await authorizeM.mutateAsync(code.trim());await initializePayment(a.authorization_token);}catch(e){setError(paymentError(e));}}
 async function checkProviderPayment(){if(!checkout||!deposit)return;setError("");try{const s=await verifyM.mutateAsync(checkout.reference);if(s.status==="paid"){const r=await depositQ.refetch();setDeposit(r.data??{...deposit,status:"completed"});await accountQ.refetch();setScreen("success");return;}if(s.status==="failed"){setScreen("failed");return;}setScreen("pending");}catch(e){setError(paymentError(e));}}
 async function completeCashApp(grantId:string){if(!checkout||!deposit)return;setError("");try{const s=await cashAppM.mutateAsync({paymentId:checkout.id,grantId});if(s.status==="paid"){const r=await depositQ.refetch();setDeposit(r.data??{...deposit,status:"completed"});await accountQ.refetch();setScreen("success");return;}setScreen("pending");}catch(e){setError(paymentError(e));}}
 function restart(){setAmount("");setDeposit(null);setCheckout(null);setCode("");setError("");setIdempotencyKey(crypto.randomUUID());setScreen("amount");}
 if(screen==="cashapp"&&checkout)return <DepositCashAppPayKit checkout={checkout} submitting={cashAppM.isPending} error={error} onApproved={g=>void completeCashApp(g)} onCancel={()=>setScreen("provider")}/>;
 if(screen==="verify"){const ok=recoveryMode?code.trim().length>=6:code.length===6;return <div className="mx-auto max-w-md text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl" style={{color:"var(--brand-accent)",background:"color-mix(in srgb, var(--brand-accent) 10%, var(--surface))"}}><ShieldCheck size={21}/></div><h1 className="mt-4 text-2xl font-semibold" style={{color:"var(--text)"}}>Verify it's you</h1><p className="mt-2 text-sm" style={{color:"var(--muted)"}}>Confirm this payment before we open the provider checkout.</p><div className="mt-6 text-left">{recoveryMode?<FormField label="Recovery code" htmlFor="deposit-recovery"><Input id="deposit-recovery" value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter a recovery code" autoFocus/></FormField>:<OtpInput value={code} onChange={setCode} disabled={authorizeM.isPending||initM.isPending}/>}</div>{error?<p className="mt-3 text-sm" style={{color:"var(--danger)"}}>{error}</p>:null}<Button className="mt-5 w-full" disabled={!ok} loading={authorizeM.isPending||initM.isPending} onClick={()=>void verifyStepUp()}>Verify and continue</Button><button type="button" className="mt-4 text-sm font-medium" style={{color:"var(--brand-accent)"}} onClick={()=>{setRecoveryMode(v=>!v);setCode("");}}>{recoveryMode?"Use authenticator code instead":"Use a recovery code instead"}</button></div>}
 if(screen==="checkout"&&checkout&&deposit)return <div className="mx-auto max-w-lg text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl" style={{color:"var(--brand-accent)",background:"color-mix(in srgb, var(--brand-accent) 10%, var(--surface))"}}><CreditCard size={24}/></div><h1 className="mt-4 text-2xl font-semibold" style={{color:"var(--text)"}}>Complete your payment</h1><p className="mt-2 text-sm leading-6" style={{color:"var(--muted)"}}>Complete the {formatCurrency(deposit.amount,deposit.currency)} payment in the secure provider checkout, then return here.</p><div className="mt-6 rounded-[var(--radius-card)] border p-5" style={{background:"var(--surface)",borderColor:"var(--border)"}}><Button className="w-full" loading={verifyM.isPending} onClick={()=>void checkProviderPayment()}>I've paid · Verify</Button><Button className="mt-2 w-full" variant="secondary" onClick={()=>window.open(checkout.authorization_url,"_blank","noopener,noreferrer")}>Reopen checkout</Button>{error?<p className="mt-4 text-sm" style={{color:"var(--danger)"}}>{error}</p>:null}</div></div>;
 if((screen==="success"||screen==="pending"||screen==="failed")&&deposit){const success=screen==="success",failed=screen==="failed";return <div className="mx-auto max-w-lg text-center"><div className="mx-auto grid size-14 place-items-center rounded-full" style={{color:failed?"var(--danger)":success?"var(--success)":"var(--warning)",background:"var(--surface-alt)"}}>{success?<CheckCircle2 size={29}/>:<CreditCard size={25}/>}</div><h1 className="mt-4 text-2xl font-semibold" style={{color:"var(--text)"}}>{success?"Money added":failed?"Payment unsuccessful":"Payment received"}</h1><p className="mt-2 text-3xl font-semibold" style={{color:"var(--text)"}}>{formatCurrency(deposit.amount,deposit.currency)}</p><p className="mt-2 text-sm leading-6" style={{color:"var(--muted)"}}>{success?"Your account balance has been credited.":failed?"No account balance was changed.":"We're waiting for provider confirmation. Your balance updates only after verification."}</p>{success&&accountQ.data?<div className="mt-5 rounded-xl border p-4 text-left" style={{background:"var(--surface)",borderColor:"var(--border)"}}><p className="text-xs" style={{color:"var(--muted)"}}>Available balance</p><p className="mt-1 text-xl font-semibold" style={{color:"var(--text)"}}>{formatCurrency(accountQ.data.available_balance,accountQ.data.currency)}</p><div className="mt-4 flex items-center justify-between gap-3 border-t pt-4" style={{borderColor:"var(--border)"}}><span className="text-sm" style={{color:"var(--muted)"}}>Deposit reference</span><CopyButton value={deposit.id} label="Copy"/></div></div>:null}{screen==="pending"?<Button className="mt-5 w-full" loading={verifyM.isPending} onClick={()=>void checkProviderPayment()}>Check status</Button>:null}{failed?<Button className="mt-5 w-full" onClick={restart}>Try again</Button>:null}<Button className="mt-2 w-full" variant="secondary" onClick={()=>navigate("/payments")}>View payments</Button></div>}
 if(screen==="provider"&&deposit){const providers=providersQ.data??[];return <div className="mx-auto max-w-2xl"><button type="button" onClick={()=>setScreen("amount")} className="mb-5 inline-flex items-center gap-2 text-sm" style={{color:"var(--muted)"}}><ArrowLeft size={17}/>Deposit amount</button><h1 className="text-2xl font-semibold" style={{color:"var(--text)"}}>Payment method</h1><p className="mt-1 text-sm" style={{color:"var(--muted)"}}>Choose a configured provider to fund your account.</p><div className="mt-6 rounded-[var(--radius-card)] border p-5" style={{background:"var(--surface)",borderColor:"var(--border)"}}><div className="mb-5 rounded-xl p-4" style={{background:"var(--surface-alt)"}}><p className="text-xs" style={{color:"var(--muted)"}}>Deposit amount</p><p className="mt-1 text-2xl font-semibold" style={{color:"var(--text)"}}>{formatCurrency(deposit.amount,deposit.currency)}</p></div>{providersQ.isPending?<div className="space-y-2">{[0,1,2].map(i=><div key={i} className="h-16 animate-pulse rounded-xl" style={{background:"var(--surface-alt)"}}/>)}</div>:providers.length===0?<ErrorState title="Deposit unavailable" description="No payment provider has been configured yet."/>:<div className="space-y-2">{providers.map(item=>{const active=item===provider;return <button key={item} type="button" onClick={()=>{setProvider(item);setError("");}} className="flex w-full items-center gap-3 rounded-xl border p-3 text-left" style={{borderColor:active?"var(--brand-accent)":"var(--border)",background:active?"color-mix(in srgb, var(--brand-accent) 8%, var(--surface))":"var(--surface)"}}><div className="grid size-10 place-items-center rounded-xl" style={{color:active?"var(--brand-accent)":"var(--muted)",background:"var(--surface-alt)"}}><ProviderIcon provider={item}/></div><div className="flex-1"><p className="font-medium" style={{color:"var(--text)"}}>{providerLabel(item)}</p><p className="mt-0.5 text-xs" style={{color:"var(--muted)"}}>Secure provider checkout</p></div><span className="grid size-5 place-items-center rounded-full border" style={{borderColor:active?"var(--brand-accent)":"var(--border)"}}>{active?<span className="size-2.5 rounded-full" style={{background:"var(--brand-accent)"}}/>:null}</span></button>})}</div>}{error?<p className="mt-4 text-sm" style={{color:"var(--danger)"}}>{error}</p>:null}<Button className="mt-5 w-full" disabled={!provider||providers.length===0} loading={initM.isPending} onClick={()=>void initializePayment()}>Continue to payment</Button></div></div>}
 return <PullToRefresh onRefresh={refresh}><div className="grid gap-6 lg:grid-cols-[minmax(0,680px)_320px] lg:items-start"><div><div className="flex items-center gap-3"><Link to={ROUTES.dashboard} className="grid size-9 place-items-center rounded-xl border" style={{color:"var(--muted)",borderColor:"var(--border)",background:"var(--surface)"}}><ArrowLeft size={17}/></Link><div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl" style={{color:"var(--text)"}}>Deposit money</h1><p className="mt-1 text-sm" style={{color:"var(--muted)"}}>Add money to your account through a configured payment provider.</p></div></div><div className="mt-6 rounded-[var(--radius-card)] border p-5 sm:p-6" style={{background:"var(--surface)",borderColor:"var(--border)",boxShadow:"var(--shadow-card)"}}>{accountQ.data?<div className="mb-5 rounded-xl p-4" style={{background:"var(--surface-alt)"}}><p className="text-xs" style={{color:"var(--muted)"}}>Available balance</p><p className="mt-1 text-xl font-semibold" style={{color:"var(--text)"}}>{formatCurrency(accountQ.data.available_balance,accountQ.data.currency)}</p></div>:null}<FormField label="Amount" htmlFor="deposit-amount"><Input id="deposit-amount" inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);setError("");}}/></FormField>{validAmount?<div className="mt-4 rounded-xl border p-4" style={{borderColor:"var(--border)",background:"var(--surface-alt)"}}><div className="flex justify-between gap-4"><span className="text-sm" style={{color:"var(--muted)"}}>You'll add</span><strong style={{color:"var(--text)"}}>{formatCurrency(numericAmount,accountQ.data?.currency??"USD")}</strong></div>{projectedBalance!==null&&accountQ.data?<div className="mt-3 flex justify-between gap-4"><span className="text-sm" style={{color:"var(--muted)"}}>Balance after payment</span><strong style={{color:"var(--success)"}}>{formatCurrency(projectedBalance,accountQ.data.currency)}</strong></div>:null}</div>:null}{error?<p className="mt-4 text-sm" style={{color:"var(--danger)"}}>{error}</p>:null}<Button className="mt-5 w-full" disabled={!validAmount} loading={createM.isPending} onClick={()=>void continueFromAmount()}>Continue</Button></div></div><aside className="hidden rounded-[var(--radius-card)] border p-5 lg:block" style={{background:"var(--surface)",borderColor:"var(--border)"}}><h2 className="font-semibold" style={{color:"var(--text)"}}>Why deposit here?</h2><div className="mt-4 space-y-3 text-sm leading-6" style={{color:"var(--muted)"}}><p>✓ Fund your account for transfers and withdrawals.</p><p>✓ Only configured providers are shown.</p><p>✓ Balance changes only after provider verification.</p><p>✓ Duplicate callbacks cannot double-credit a deposit.</p></div></aside></div></PullToRefresh>;
}
