import { ArrowDownLeft, ArrowUpRight } from "lucide-react";
import { EmptyState, StatusBadge } from "@/components/common";
import type { TransactionItem } from "@/types/transactions";
import { formatCurrency } from "@/utils/formatCurrency";
import { formatDateTime } from "@/utils/formatDateTime";

function tone(s:string){return s==="completed"?"success" as const:s==="pending"?"warning" as const:s==="failed"?"danger" as const:s==="reversed"?"info" as const:"neutral" as const}
function label(i:TransactionItem){return i.description?.trim() || i.type.split("_").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ")}
export default function TransactionList({items,onSelect}:{items:TransactionItem[];onSelect:(item:TransactionItem)=>void}){
 if(!items.length)return <EmptyState title="No matching activity" description="Your account activity will appear here. Try changing the filters if you expected a result."/>;
 return <div className="overflow-hidden rounded-[var(--radius-card)] border" style={{background:"var(--surface)",borderColor:"var(--border)",boxShadow:"var(--shadow-card)"}}>
  <div className="divide-y sm:hidden" style={{borderColor:"var(--border)"}}>{items.map(i=>{const credit=i.direction==="credit",Icon=credit?ArrowDownLeft:ArrowUpRight;return <button key={`${i.id}-${i.direction}`} type="button" onClick={()=>onSelect(i)} className="flex w-full items-center gap-3 p-4 text-left" style={{borderColor:"var(--border)"}}><div className="grid size-9 shrink-0 place-items-center rounded-xl" style={{color:credit?"var(--success)":"var(--danger)",background:`color-mix(in srgb, ${credit?"var(--success)":"var(--danger)"} 10%, var(--surface))`}}><Icon size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium" style={{color:"var(--text)"}}>{label(i)}</p><p className="mt-0.5 text-xs" style={{color:"var(--muted)"}}>{formatDateTime(i.created_at)}</p>{i.status!=="completed"?<div className="mt-2"><StatusBadge tone={tone(i.status)}>{i.status[0].toUpperCase()+i.status.slice(1)}</StatusBadge></div>:null}</div><span className="text-sm font-semibold tabular-nums" style={{color:credit?"var(--success)":"var(--danger)"}}>{credit?"+":"-"}{formatCurrency(i.amount,i.currency)}</span></button>})}</div>
  <div className="hidden sm:block"><div className="grid grid-cols-[minmax(0,1.5fr)_minmax(150px,.8fr)_110px_130px] gap-4 border-b px-4 py-3 text-xs font-medium" style={{background:"var(--surface-alt)",borderColor:"var(--border)",color:"var(--muted)"}}><span>Description</span><span>Date</span><span>Status</span><span className="text-right">Amount</span></div>{items.map(i=>{const credit=i.direction==="credit";return <button key={`${i.id}-${i.direction}`} type="button" onClick={()=>onSelect(i)} className="grid w-full grid-cols-[minmax(0,1.5fr)_minmax(150px,.8fr)_110px_130px] items-center gap-4 border-b px-4 py-3 text-left last:border-b-0" style={{borderColor:"var(--border)"}}><div className="min-w-0"><p className="truncate text-sm font-medium" style={{color:"var(--text)"}}>{label(i)}</p><p className="truncate text-xs" style={{color:"var(--muted)"}}>{i.reference}</p></div><span className="text-sm" style={{color:"var(--muted)"}}>{formatDateTime(i.created_at)}</span><StatusBadge tone={tone(i.status)}>{i.status[0].toUpperCase()+i.status.slice(1)}</StatusBadge><span className="text-right text-sm font-semibold tabular-nums" style={{color:credit?"var(--success)":"var(--danger)"}}>{credit?"+":"-"}{formatCurrency(i.amount,i.currency)}</span></button>})}</div>
 </div>}
