import { ArrowDownLeft, ArrowUpRight, X } from "lucide-react";
import { CopyButton, ErrorState, StatusBadge } from "@/components/common";
import type { TransactionItem } from "@/types/transactions";
import { formatCurrency } from "@/utils/formatCurrency";
import { formatDateTime } from "@/utils/formatDateTime";
function tone(s:string){return s==="completed"?"success" as const:s==="pending"?"warning" as const:s==="failed"?"danger" as const:"info" as const}
export default function TransactionDetailPanel({item,loading,error,onClose,onRetry}:{item?:TransactionItem;loading:boolean;error:boolean;onClose:()=>void;onRetry:()=>void}){
 return <div className="fixed inset-0 z-50 bg-black/35 lg:flex lg:justify-end" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="ml-auto min-h-full w-full overflow-y-auto border-l sm:max-w-md" style={{background:"var(--surface)",borderColor:"var(--border)"}}><div className="flex items-center justify-between border-b px-5 py-4" style={{borderColor:"var(--border)"}}><h2 className="font-semibold" style={{color:"var(--text)"}}>Transaction details</h2><button onClick={onClose} className="grid size-9 place-items-center rounded-lg" style={{color:"var(--muted)"}} aria-label="Close"><X size={18}/></button></div><div className="p-5">{loading?<div className="space-y-4"><div className="h-20 animate-pulse rounded-xl" style={{background:"var(--surface-alt)"}}/><div className="h-48 animate-pulse rounded-xl" style={{background:"var(--surface-alt)"}}/></div>:error?<ErrorState title="Could not load transaction" description="The transaction details are temporarily unavailable." onAction={onRetry}/>:item?<Detail item={item}/>:null}</div></aside></div>
}
function Detail({item}:{item:TransactionItem}){const credit=item.direction==="credit",Icon=credit?ArrowDownLeft:ArrowUpRight;return <div><div className="text-center"><div className="mx-auto grid size-12 place-items-center rounded-full" style={{color:credit?"var(--success)":"var(--danger)",background:`color-mix(in srgb, ${credit?"var(--success)":"var(--danger)"} 11%, var(--surface))`}}><Icon size={21}/></div><p className="mt-3 text-2xl font-semibold" style={{color:credit?"var(--success)":"var(--text)"}}>{credit?"+":"-"}{formatCurrency(item.amount,item.currency)}</p><div className="mt-2"><StatusBadge tone={tone(item.status)}>{item.status[0].toUpperCase()+item.status.slice(1)}</StatusBadge></div></div><dl className="mt-7 divide-y rounded-[var(--radius-card)] border px-4" style={{borderColor:"var(--border)"}}><Row label="Description" value={item.description||item.type.replaceAll("_"," ")}/><div className="flex items-center justify-between gap-3 py-4"><div><dt className="text-xs" style={{color:"var(--muted)"}}>Reference</dt><dd className="mt-1 break-all text-sm font-medium" style={{color:"var(--text)"}}>{item.reference}</dd></div><CopyButton value={item.reference} successMessage="Transaction reference copied."/></div><Row label="Date" value={formatDateTime(item.created_at)}/><Row label="Balance after" value={formatCurrency(item.balance_after,item.currency)}/><Row label="Direction" value={credit?"Money in":"Money out"}/></dl></div>}
function Row({label,value}:{label:string;value:string}){return <div className="py-4"><dt className="text-xs" style={{color:"var(--muted)"}}>{label}</dt><dd className="mt-1 text-sm font-medium capitalize" style={{color:"var(--text)"}}>{value}</dd></div>}
