"""type payment providers and channels

Revision ID: b0f56d4a36f9
Revises: 2c1ac5786e16
Create Date: 2026-09-13 11:22:29.955243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f56d4a36f9'
down_revision: Union[str, Sequence[str], None] = '2c1ac5786e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('channel', sa.Enum('card', 'bank', 'bank_transfer', 'mobile_money', 'ussd', 'qr', 'wallet', 'paypal', 'venmo', 'cash_app', 'other', name='payment_channel', native_enum=False, create_constraint=True, length=30), nullable=True))
    op.add_column('payments', sa.Column('provider_channel', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_payments_channel'), 'payments', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_channel'), table_name='payments')
    op.drop_column('payments', 'provider_channel')
    op.drop_column('payments', 'channel')
    # ### end Alembic commands ###
