import { ArrowRightLeft, FileText } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";

import { getAdminTransfer, getAdminTransfers } from "@/api/admin";
import Drawer from "@/components/common/Drawer";
import Pagination from "@/components/common/Pagination";
import ExportCsvButton from "@/components/common/ExportCsvButton";
import StatusBadge from "@/components/common/StatusBadge";
import FinancialEmptyState from "@/components/financial/FinancialEmptyState";
import { DetailRow, FilterSelect, LedgerTable, RefValue, SearchBox } from "@/components/financial/FinancialTableParts";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import { formatCurrency, formatDateTime } from "@/utils/format";

const LIMIT = 20;

export default function AdminTransfersPage() {
  const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [offset,setOffset]=useState(0); const [selectedId,setSelectedId]=useState<string|null>(null);
  const q=useDebouncedValue(search.trim(),350); useEffect(()=>setOffset(0),[q,status]);
  const listQ=useQuery({queryKey:["admin","transfers",q,status,offset],queryFn:()=>getAdminTransfers({q:q||undefined,status:status||undefined,limit:LIMIT,offset})});
  const detailQ=useQuery({queryKey:["admin","transfer",selectedId],queryFn:()=>getAdminTransfer(selectedId!),enabled:Boolean(selectedId)});
  return <div className="space-y-5">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-[-0.03em]" style={{color:"var(--text)"}}>Transfers</h1><p className="mt-1 text-sm" style={{color:"var(--muted)"}}>Inspect internal customer-to-customer transfers and their ledger impact.</p></div><ExportCsvButton resource="transfers" params={{q:q||undefined,status:status||undefined}} /></header>
    <section className="overflow-hidden rounded-[var(--radius-card)] border" style={{background:"var(--surface)",borderColor:"var(--border)"}}>
      <div className="flex flex-col gap-3 p-4 lg:flex-row"><SearchBox value={search} onChange={setSearch} placeholder="Search reference, sender, recipient or account"/><FilterSelect value={status} onChange={setStatus} ariaLabel="Transfer status"><option value="">All statuses</option><option value="completed">Completed</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="reversed">Reversed</option></FilterSelect></div>
      {listQ.isLoading?<div className="border-t p-8 text-center text-sm" style={{borderColor:"var(--border)",color:"var(--muted)"}}>Loading transfers...</div>:listQ.isError?<div className="border-t p-8 text-center text-sm" style={{borderColor:"var(--border)",color:"var(--danger)"}}>Transfers could not be loaded.</div>:listQ.data?.items.length?<>
        <div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[900px] text-left text-sm"><thead style={{background:"var(--surface-alt)"}}><tr>{['Reference','Sender','Recipient','Amount','Status','Date',''].map(h=><th key={h} className="border-y px-4 py-3 text-xs font-semibold" style={{color:"var(--muted)",borderColor:"var(--border)"}}>{h}</th>)}</tr></thead><tbody>{listQ.data.items.map(item=><tr key={item.id} className="border-b last:border-b-0" style={{borderColor:"var(--border)"}}><td className="px-4 py-3 font-mono text-xs" style={{color:"var(--text)"}}>{item.reference}</td><td className="px-4 py-3"><p style={{color:"var(--text)"}}>{item.sender.name}</p><p className="font-mono text-xs" style={{color:"var(--muted)"}}>{item.sender_account.account_number}</p></td><td className="px-4 py-3"><p style={{color:"var(--text)"}}>{item.recipient.name}</p><p className="font-mono text-xs" style={{color:"var(--muted)"}}>{item.recipient_account.account_number}</p></td><td className="px-4 py-3 font-semibold" style={{color:"var(--text)"}}>{formatCurrency(item.amount,item.currency)}</td><td className="px-4 py-3"><StatusBadge label={item.status} tone={item.status==='completed'?'success':item.status==='failed'?'danger':'warning'}/></td><td className="px-4 py-3 text-xs" style={{color:"var(--muted)"}}>{formatDateTime(item.created_at)}</td><td className="px-4 py-3 text-right"><button className="rounded-lg border px-3 py-2 text-xs font-semibold" style={{color:"var(--brand-accent)",borderColor:"var(--border)"}} onClick={()=>setSelectedId(item.id)}>View</button></td></tr>)}</tbody></table></div>
        <div className="grid gap-3 border-t p-4 lg:hidden" style={{borderColor:"var(--border)"}}>{listQ.data.items.map(item=><button key={item.id} className="rounded-xl border p-4 text-left" style={{borderColor:"var(--border)"}} onClick={()=>setSelectedId(item.id)}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium" style={{color:"var(--text)"}}>{item.sender.name} → {item.recipient.name}</p><p className="mt-1 font-mono text-xs" style={{color:"var(--muted)"}}>{item.reference}</p></div><ArrowRightLeft size={18} style={{color:"var(--muted)"}}/></div><div className="mt-3 flex items-center justify-between"><strong style={{color:"var(--text)"}}>{formatCurrency(item.amount,item.currency)}</strong><StatusBadge label={item.status} tone={item.status==='completed'?'success':item.status==='failed'?'danger':'warning'}/></div></button>)}</div><Pagination total={listQ.data.page.total} limit={LIMIT} offset={offset} onOffsetChange={setOffset}/>
      </>:<FinancialEmptyState title="No transfers found" description="Adjust the search or status filter."/>}
    </section>
    <Drawer open={Boolean(selectedId)} title="Transfer details" onClose={()=>setSelectedId(null)}>{detailQ.isLoading?<div className="p-6 text-sm" style={{color:"var(--muted)"}}>Loading transfer...</div>:detailQ.data?<div className="space-y-6 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><RefValue value={detailQ.data.reference}/><StatusBadge label={detailQ.data.status} tone={detailQ.data.status==='completed'?'success':detailQ.data.status==='failed'?'danger':'warning'}/></div><p className="mt-2 text-xs" style={{color:"var(--muted)"}}>{formatDateTime(detailQ.data.created_at)}</p></div><strong className="text-xl" style={{color:"var(--text)"}}>{formatCurrency(detailQ.data.amount,detailQ.data.currency)}</strong></div><div className="grid gap-3 sm:grid-cols-2"><section className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><h3 className="text-sm font-semibold" style={{color:"var(--text)"}}>Sender</h3><DetailRow label="Customer">{detailQ.data.sender.name}</DetailRow><DetailRow label="Email">{detailQ.data.sender.email}</DetailRow><DetailRow label="Account"><RefValue value={detailQ.data.sender_account.account_number} label="Account number"/></DetailRow></section><section className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><h3 className="text-sm font-semibold" style={{color:"var(--text)"}}>Recipient</h3><DetailRow label="Customer">{detailQ.data.recipient.name}</DetailRow><DetailRow label="Email">{detailQ.data.recipient.email}</DetailRow><DetailRow label="Account"><RefValue value={detailQ.data.recipient_account.account_number} label="Account number"/></DetailRow></section></div><section className="rounded-xl border p-4" style={{borderColor:"var(--border)"}}><DetailRow label="Narration">{detailQ.data.narration||'—'}</DetailRow><DetailRow label="Transaction ID">{detailQ.data.transaction_id}</DetailRow></section><section><div className="mb-3 flex items-center gap-2"><FileText size={17} style={{color:"var(--brand-accent)"}}/><h3 className="font-semibold" style={{color:"var(--text)"}}>Ledger entries</h3></div><LedgerTable entries={detailQ.data.ledger_entries}/></section></div>:selectedId?<div className="p-6 text-sm" style={{color:"var(--danger)"}}>Transfer detail could not be loaded.</div>:null}</Drawer>
  </div>;
}
