import { ArrowLeft, CreditCard, Landmark } from "lucide-react";
import { Link } from "react-router-dom";
import CopyButton from "@/components/common/CopyButton";
import type { PaymentHistoryItem } from "@/types/payments";
import { formatCurrency } from "@/utils/formatCurrency";
import { formatDateTime } from "@/utils/formatDateTime";
import { providerLabel, purposeLabel, relatedRoute } from "@/utils/payment";
import PaymentStatusBadge from "./PaymentStatusBadge";
export default function PaymentDetail({payment,onBack}:{payment:PaymentHistoryItem;onBack:()=>void}){const related=relatedRoute(payment);return <div className="mx-auto max-w-2xl"><button type="button" onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-sm" style={{color:"var(--muted)"}}><ArrowLeft size={17}/>Payments</button><div className="text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl" style={{color:"var(--brand-accent)",background:"var(--surface-alt)"}}>{payment.purpose==="deposit"?<Landmark size={21}/>:<CreditCard size={21}/>}</div><p className="mt-4 text-3xl font-semibold" style={{color:"var(--text)"}}>{formatCurrency(payment.amount,payment.currency)}</p><div className="mt-2"><PaymentStatusBadge status={payment.status}/></div></div><div className="mt-6 rounded-[var(--radius-card)] border p-5 sm:p-6" style={{background:"var(--surface)",borderColor:"var(--border)"}}><dl className="space-y-4 text-sm"><div className="flex justify-between gap-4"><dt style={{color:"var(--muted)"}}>Purpose</dt><dd className="font-medium" style={{color:"var(--text)"}}>{purposeLabel(payment.purpose)}</dd></div><div className="flex justify-between gap-4"><dt style={{color:"var(--muted)"}}>Provider</dt><dd style={{color:"var(--text)"}}>{providerLabel(payment.provider)}</dd></div><div className="flex items-center justify-between gap-4"><dt style={{color:"var(--muted)"}}>Reference</dt><dd className="flex min-w-0 items-center gap-2"><span className="max-w-[220px] truncate" style={{color:"var(--text)"}}>{payment.reference}</span><CopyButton value={payment.reference} label="Copy"/></dd></div><div className="flex justify-between gap-4"><dt style={{color:"var(--muted)"}}>Date</dt><dd style={{color:"var(--text)"}}>{formatDateTime(payment.created_at)}</dd></div></dl>{related?<Link to={related} className="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-[var(--radius-control)] border px-4 text-sm font-medium" style={{color:"var(--text)",borderColor:"var(--border)",background:"var(--surface-alt)"}}>{payment.purpose==="deposit"?"View deposits":"View withdrawal"}</Link>:null}</div></div>}
