export const ROUTES = {
  landing: "/",
  dashboard: "/dashboard",
  login: "/login",
  loginLocked: "/login/locked",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  twoFactor: "/2fa",
  transfer: "/transfer",
  activity: "/activity",
  withdraw: "/withdraw",
  deposit: "/deposit",
  payments: "/payments",
  profile: "/profile",
  security: "/security",
  securityPassword: "/security/password",
  securityTwoFactor: "/security/2fa",
  securitySessions: "/security/sessions",
  securityActivity: "/security/activity",
  support: "/support",
} as const;
